import {
  CONTROLLER_MIN_SEGMENT,
  buildObstacleAwareRoute,
  sanitizeRouteForController,
} from "./zonePlannerRouting";
import {
  CANVAS_HEIGHT,
  CANVAS_WIDTH,
  DRAWING_HEIGHT,
  DRAWING_LEFT,
  DRAWING_TOP,
  DRAWING_WIDTH,
  HALF_HEIGHT,
  HALF_WIDTH,
  MAP_PADDING,
  MAP_WORLD_HEIGHT,
  MAP_WORLD_WIDTH,
  SCALE,
  canvasToWorld,
  isInsideMap,
  worldToCanvas,
} from "./zonePlannerCoordinates";
import {
  dist,
  pointEquals,
  pointInAnyPolygon,
  pointInPolygon,
  segmentsIntersect,
} from "./zonePlannerGeometry";
import {
  ROUTE_CLEARANCE_MARGIN,
  SAFE_POINT_MARGIN,
  projectPointOutsidePolygons,
  routeCrossesAnyLimitPolygon,
} from "./zonePlannerPolygons";
import {
  DEFAULT_POINT_TASK,
  DEFAULT_SURFACE_ZONES,
  POINT_KIND_META,
  POINT_KIND_OPTIONS,
  POINT_TASKS,
  getZoneColor,
} from "./zonePlannerPresentation";
import {
  drawDiamond,
  drawPlannerBackground,
} from "../features/planner/services/plannerCanvasRenderer";

export {
  CANVAS_HEIGHT,
  CANVAS_WIDTH,
  DRAWING_HEIGHT,
  DRAWING_LEFT,
  DRAWING_TOP,
  DRAWING_WIDTH,
  HALF_HEIGHT,
  HALF_WIDTH,
  MAP_PADDING,
  MAP_WORLD_HEIGHT,
  MAP_WORLD_WIDTH,
  SCALE,
  canvasToWorld,
  isInsideMap,
  worldToCanvas,
  dist,
  pointEquals,
  pointInAnyPolygon,
  pointInPolygon,
  segmentsIntersect,
  ROUTE_CLEARANCE_MARGIN,
  SAFE_POINT_MARGIN,
  projectPointOutsidePolygons,
  routeCrossesAnyLimitPolygon,
  buildObstacleAwareRoute,
  CONTROLLER_MIN_SEGMENT,
  sanitizeRouteForController,
  DEFAULT_POINT_TASK,
  DEFAULT_SURFACE_ZONES,
  POINT_KIND_META,
  POINT_KIND_OPTIONS,
  POINT_TASKS,
  getZoneColor,
  drawDiamond,
  drawPlannerBackground,
};
