import { MAPPING_SURVEY_MODES } from "./runtimeCommands";

export const createCanvasProps = ({ state, runtime, derived, actions }) => ({
  canvasRef: state.canvas?.canvasRef,
  plannerModel: derived.plannerModel,
  optimizedRoute: state.route?.optimizedRoute,
  hoveredPointIndex: state.interaction?.hoveredPointIndex,
  telemetry: runtime.telemetry,
  onCanvasClick: actions.addPointFromCanvas,
  onCanvasMouseDown: actions.handleCanvasMouseDown,
  onCanvasMouseMove: actions.handleCanvasMouseMove,
  onCanvasMouseUp: actions.finishDragging,
  onCanvasMouseLeave: actions.finishDragging,
});

export const createLeftSidebarProps = ({ state, runtime, derived, actions }) => {
  const { algorithm = {}, energy = {}, interaction = {}, route = {}, surfaces = {} } = state;
  const plannerModel = derived.plannerModel || {};
  const viewModel = derived.viewModel || {};

  return {
    onImportFile: actions.handleImportFile,
    activePointKind: interaction.activePointKind,
    onActivePointKindChange: interaction.setActivePointKind,
    onClearVisitPoints: () => actions.clearPoints?.("visit"),
    onClearChargePoints: () => actions.clearPoints?.("charge"),
    onClearLimitPoints: () => actions.clearPoints?.("limit"),
    routeTaskKey: algorithm.routeTaskKey,
    onRouteTaskChange: actions.handleRouteTaskChange,
    algorithmKey: algorithm.algorithmKey,
    onAlgorithmChange: actions.handleAlgorithmChange,
    status: route.status,
    energyWarning: route.energyWarning,
    routeBlocked: plannerModel.routeBlocked,
    algorithmFields: viewModel.algorithmFields,
    selectedAlgorithmParams: viewModel.selectedAlgorithmParams,
    onAlgorithmParamChange: actions.updateAlgorithmParam,
    isOptimizing: route.isOptimizing,
    onOptimizeRoute: actions.optimizeRoute,
    onSendRoute: actions.sendRoute,
    onAddRandomObstacle: actions.addRandomObstacle,
    onClearAll: () => actions.clearPoints?.(),
    hasRoute: (route.optimizedRoute?.length || 0) > 0,
    routeLength: plannerModel.routeLength,
    visitCount: plannerModel.visitEntries?.length,
    chargeCount: plannerModel.chargeEntries?.length,
    zoneCount: plannerModel.zoneEntries?.length,
    polygonCount: plannerModel.polygons?.length,
    adjustedVisitCount: plannerModel.adjustedVisits?.length,
    activeZoneName: plannerModel.activeZoneName,
    batteryRangeInput: energy.batteryRangeInput,
    onBatteryRangeChange: energy.handleBatteryRangeChange,
    onBatteryRangeBlur: energy.handleBatteryRangeBlur,
    cruiseSpeedMps: energy.cruiseSpeedMps,
    cruiseSpeedInput: energy.cruiseSpeedInput,
    onCruiseSpeedChange: energy.handleCruiseSpeedChange,
    onCruiseSpeedBlur: energy.handleCruiseSpeedBlur,
    payloadKg: energy.payloadKg,
    payloadInput: energy.payloadInput,
    onPayloadChange: energy.handlePayloadChange,
    onPayloadBlur: energy.handlePayloadBlur,
    routeEnergyStats: energy.routeEnergyStats,
    routeInfluenceRows: derived.routeInfluenceRows,
    routeTiming: runtime.routeTiming?.display,
    surfaceZones: surfaces.surfaceZones,
    activeSurfaceZoneId: surfaces.activeSurfaceZoneId,
    activeSurfaceZone: viewModel.activeSurfaceZone,
    activeSurfaceProfileKey: surfaces.activeSurfaceProfileKey,
    onActiveSurfaceProfileChange: actions.updateActiveSurfaceProfile,
    onCreateSurfaceZone: actions.createSurfaceZone,
    onSelectSurfaceZone: actions.selectSurfaceZone,
    onToggleSurfaceZoneClosed: actions.toggleSurfaceZoneClosed,
    onClearSurfaceZone: actions.clearSurfaceZone,
    onRemoveSurfaceZone: actions.removeSurfaceZone,
    onClearAllSurfaceZones: actions.clearAllSurfaceZones,
  };
};

export const createRightSidebarProps = ({ state, runtime, derived, actions }) => {
  const { interaction = {}, limits = {}, mapping = {} } = state;
  const plannerModel = derived.plannerModel || {};

  return {
    activeZone: plannerModel.activeZone,
    activeZoneName: plannerModel.activeZoneName,
    activeLimitZoneId: limits.activeLimitZoneId,
    zoneEntries: plannerModel.zoneEntries,
    visitEntries: plannerModel.visitEntries,
    chargeEntries: plannerModel.chargeEntries,
    plannedVisitEntries: plannerModel.plannedVisitEntries,
    expandedPoint: interaction.expandedPoint,
    hoveredPointIndex: interaction.hoveredPointIndex,
    visitsInsideLimitCount: plannerModel.visitsInsideLimit?.length,
    polygonCount: plannerModel.polygons?.length,
    adjustedVisitCount: plannerModel.adjustedVisits?.length,
    routeBlocked: plannerModel.routeBlocked,
    telemetry: derived.telemetryForSidebar,
    telemetryWsUp: runtime.telemetryWsUp,
    routeWsUp: runtime.routeWsUp,
    solverApiUp: runtime.solverApiUp,
    mappingSurveyMode: mapping.mappingSurveyMode,
    mappingSurveyModes: MAPPING_SURVEY_MODES,
    onMappingSurveyModeChange: mapping.setMappingSurveyMode,
    mapExportPromptOpen: interaction.mapExportPromptOpen,
    onStartMappingSurvey: actions.startMappingSurvey,
    onRequestMapExport: actions.requestMapExport,
    onExportMapVariant: actions.exportMapImage,
    onCancelMapExport: () => interaction.setMapExportPromptOpen?.(false),
    onCreateZone: actions.createZone,
    onSelectZone: actions.selectZone,
    onToggleZoneClosed: actions.toggleZoneClosed,
    onClearZone: actions.clearZone,
    onRemoveZone: actions.removeZone,
    onToggleExpandedPoint: interaction.setExpandedPoint,
    onHoverPoint: interaction.setHoveredPointIndex,
    onDeletePoint: actions.deletePoint,
    onUpdatePointTask: actions.updatePointTask,
  };
};
