#include "controller_control_config.h"

#define CONTROLLER_PI 3.14159265358979323846

ControllerControlConfig controller_control_config_default(void) {
  const ControllerControlConfig config = {
      .time_step_ms = 16,
      .drive = {
          .wheel_radius = 0.05,
          .wheel_base_longitudinal = 0.228,
          .wheel_base_lateral = 0.158,
          .max_wheel_speed_rad_s = 18.0,
          .acceleration_limit_rad_s2 = 150.0,
          .deceleration_limit_rad_s2 = 220.0,
      },
      .navigation = {
          .runtime = {
              .position_tolerance = 0.05,
              .heading_tolerance_rad = 0.08,
              .zone_clearance = 0.32,
              .relocation_distance = 0.45,
              .relocation_heading_rad = 1.20,
          },
          .tracking = {
              .final_align_distance = 0.18,
              .heading_tolerance_rad = 0.08,
              .track_slow_radius = 0.22,
              .turn_exit_error_rad = 0.12,
              .track_reenter_turn_rad = 0.56,
              .turn_enter_error_rad = 0.42,
              .turn_heading_gain = 3.8,
              .track_heading_gain = 3.0,
              .final_align_gain = 3.4,
              .track_min_linear_speed = 0.045,
              .min_angular_command = 0.28,
              .position_tolerance = 0.05,
          },
          .lidar = {
              .track_caution_range = 1.45,
              .avoid_stop_range = 0.31,
              .track_side_bias_range = 0.66,
              .avoid_side_danger_range = 0.15,
              .track_hard_priority_range = 1.24,
              .avoid_side_trigger_range = 0.36,
              .max_heading_bias = 0.40,
              .priority_switch_margin = 0.18,
              .priority_center_margin = 0.08,
              .priority_hold_steps = 18,
              .expected_wall_soft_stop_range = 0.24,
              .expected_wall_slowdown_range = 0.46,
          },
      },
      .perception = {
          .navigation = {
              .camera_range_epsilon = 1e-9,
              .camera_range_fallback = 1.55,
              .camera_min_fov = 0.8,
              .camera_front_fov_factor = 0.46,
              .camera_range_margin = 0.18,
              .camera_min_score = 0.025,
              .camera_min_detection_count = 3,
              .camera_offset_deadband = 0.08,
              .avoidance = {
                  .max_trace_range = 3.0,
                  .track_caution_range = 1.45,
                  .expected_wall_soft_stop_range = 0.24,
                  .expected_wall_slowdown_range = 0.46,
                  .pass_center_clear_range = 0.78,
                  .pass_gap_max_angle_rad = 0.54,
                  .pass_side_danger_range = 0.18,
                  .avoid_side_trigger_range = 0.36,
                  .track_hard_priority_range = 1.24,
                  .reflex_side_release_range = 0.62,
                  .avoid_recover_range = 1.35,
                  .avoid_trigger_range = 1.18,
                  .avoid_stop_range = 0.31,
                  .track_slow_range = 1.12,
              },
          },
      },
      .mapping = {
          .grid_cell_m = 0.25,
          .max_boundary_points = 4096,
          .contour_offset_m = 0.45,
          .interior_offset_m = 0.70,
          .strip_m = 1.10,
          .min_contour_step_m = 1.15,
          .max_contour_step_m = 1.45,
          .min_strip_length_m = 0.65,
          .rdp_epsilon_m = 0.34,
          .map_obstacle_clearance_m = 0.45,
          .max_extent_x_m = 22.0,
          .max_extent_y_m = 17.0,
          .obstacle_scan_radius_m = 0.88,
          .obstacle_scan_points = 10,
          .obstacle_scan_cooldown_steps = 260,
          .obstacle_scan_min_repeat_distance_m = 1.05,
          .avoidance_replan_steps = 140,
          .avoidance_no_progress_steps = 60,
          .avoidance_max_steps = 360,
          .avoidance_loop_radius_m = 0.48,
          .avoidance_progress_epsilon_m = 0.035,
          .avoidance_orbit_heading_rad = CONTROLLER_PI * 2.15,
          .replan_cooldown_steps = 160,
          .escape_scan_ahead = 72,
          .escape_min_target_distance_m = 0.72,
          .escape_obstacle_clearance_m = 0.58,
          .escape_segment_clearance_m = 0.46,
      },
      .avoidance = {
          .start = {
              .switch_margin = 0.18,
              .initial_hold_steps = 18,
              .priority_hold_steps = 18,
              .detour = {
                  .forward_distance = 0.72,
                  .max_distance = 1.35,
                  .side_distance = 0.54,
              },
          },
          .progress = {
              .stuck_pose_epsilon = 0.004,
              .stuck_progress_epsilon = 0.001,
              .best_progress_epsilon = 0.035,
              .min_contour_steps = 18,
              .detour_reached_distance = 0.26,
          },
          .lifecycle = {
              .min_contour_steps = 18,
              .leave_progress = 0.16,
              .leave_heading_rad = 0.44,
              .avoid_stop_range = 0.31,
              .orbit_heading_rad = CONTROLLER_PI * 2.15,
              .no_progress_steps = 60,
              .replan_steps = 140,
              .max_steps = 360,
              .loop_radius = 0.48,
              .free_space_recovery_steps = 10,
              .clear_steps = 12,
          },
          .command = {
              .avoid_recover_range = 1.35,
              .avoid_stop_range = 0.31,
              .avoid_reverse_range = 0.21,
              .gap_min_range = 0.46,
              .track_caution_range = 1.45,
              .track_side_bias_range = 0.66,
              .pass_side_danger_range = 0.18,
              .pass_center_clear_range = 0.78,
              .pass_cruise_speed_factor = 0.88,
              .pass_steer_gain = 2.2,
              .min_angular_command = 0.28,
              .gap_switch_range_bonus = 0.14,
              .stuck_steps_limit = 24,
          },
      },
      .schedule = {
          .lifecycle = {
              .zone_reload_interval = 10,
              .route_reload_interval = 20,
              .motion_reload_interval = 20,
              .runtime_command_reload_interval = 6,
              .map_write_interval = 60,
              .camera_capture_interval = 4,
              .camera_write_interval = 12,
          },
      },
  };
  return config;
}
